name: dotnet-core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test --no-restore --logger:"console;verbosity=normal" --collect:"XPlat Code Coverage"
    - name: Coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./Quber.Tests/TestResults/*/coverage.cobertura.xml
        verbose: true # optional (default = false)
